### ISSUE TITLE
Rework of productivity/speed

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/startupcompany#125]
Right now the productivity & speed is the same, I'd like to see this be reworked. 

The productivity shouldn't only depend on the mood penalty & speed, instead I'd like to see the workers different feelings & experience to be the base of the productivity. Therefore I'd like to make the productivity a little bit more complex but at the same time easier to monitor. 

So my idea is that a worker starts for example at:
[Speed]50/130%
30/100%(Low office bonus, low, alot of depressed co-workers etc)
50/100% (Too much work, no vacation)

This can then be raised for example by upgrading the workers speed, buying more office bonus, and by making OTHER workers happier, and also be smart when you choose jobs. It's still important that a person goes to vacation as it will make the exhaustion more close to 100/100%. 

![hovgaard](https://cloud.githubusercontent.com/assets/8394703/19454149/3df49300-94b8-11e6-9ceb-f82f1c095df2.png)

Company Mood should also be calculated with the Office Bonus. 

IDEAS?! Discuss please.

**Comment by jhovgaard** [comment]
The idea is great, but the question is if the feature is worth the time. It will require a lot of work and a lot of possible bugs. 

I'll get back to this.

**Comment by InDieTasten** [comment]
Also, you need some way to let the player know what factors are considered in the productivity. So either you need to explain it in detail in some view, or you give hints in form of messages. Whenever someone gets unproductive, his manager (in case he has one) will ask you to let him go on vacation, or to improve the office. whatever it is, that is pulling down the productivity/mood the most at that time.

**Comment by BrutalCSkakan** [comment]
That will be an easy fix tho. 

Don't we already have most of the variables in the game? Is this really such a big task?

**Comment by InDieTasten** [comment]
It needs to be balanced. Finding a good balance takes time. Also, the player needs to be told why his employee's productivity is where it is. Otherwise, it will just seem like a random thing by chance, which the player could blame on the game. I also don't really get the chart you've drawn with that arrow thing and the speed/company mood/exhaustion.

**Comment by jhovgaard** [comment]
I think this kinda adds up as an additional feature to the current mood indicator. Like this could be shown when hovering the mood bar. It would work as a helper for improving mood degeneration.

**Comment by markrichey** [comment]
Could we implement a version of the 70/30 rule? So against a manager you could choose management styles / strategy and select either 70/30 as a hard coded option or enter your own values. The employee then works on his task X % of his working day and "enjoys" free time for the rest. That free time can increase the mood and at the end of the employees free time there is a % chance (not sure how best to calculate this) that the task there assigned to benefits from a boost, this boost represents development of a new tool, method or process (made in the free time) that allows a task to be done quicker than normal.

**Comment by jhovgaard** [comment]
@markrichey That's another even more interesting way of doing it.

I think the percentages will be too complicated for the player to understand, but what we could instead is putting in a "Friendly, Moderate, Aggressive" option. Friendly: Happy slow devs. Aggressive: Fast unhappy devs.

What do you guy think? Not exactly what @BrutalCSkakan originally suggested but still a nice addition.

**Comment by WodeCraft** [comment]
@markrichey @jhovgaard It would be great that you could tweak the productivity this way as well

No matter which solution (either the percentage or the description) you would need a way to inform the players about how it works. The only positive think about going by the percentage is that it leaves room for future improvements.

Just my 2 cents

**Comment by markrichey** [comment]
@jhovgaard Agree with that!

 I think it would be good if an employee has a "burnout bar" which indicates how close to becoming useless they are, the aggressive dev increases the bar and the slow dev reduces it. I think if that's the direction you go the slow dev should bring the bar down slower than the aggressive dev increases it, this way you give the player the feeling that there was a consequence in putting the dev in aggressive mode. 

One final thing, and I apologies because I am making you lots of work, I would suggest that if an employee is more than 50% burnt out they cant be fired or dismissed without incurring a sizeable financial penalty. This will prevent the player from working there people into the ground then just ditching them?

Keep up the great work!
