### ISSUE TITLE
Inbox: Right click to delete mail

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/startupcompany#210]
When you right-click a message, then it should be removed.

**Comment by jhovgaard** [comment]
Keeping this open for up-votes.

**Comment by SirFinrod** [comment]
This is a good suggestion i think because sometimes i need to delete mass amount of them and its kinda painfull to open them and delete them one by one but rather then right click this can be better 

![deletereposition](https://cloud.githubusercontent.com/assets/25222894/22182970/a0279cdc-e0c3-11e6-8676-48869daae85f.png)


This way we can prevent misclicks.

**Comment by prempador** [comment]
Well, last stream we got some fixes where the game asks for permission to change something (Developer changing the module their working on, will ask you if you really want to change it) and now we want a simple click do delete emails. 
When adding this button we should at least get a warning too. And if we get a warning it has the same click count if you open the mail and delete it. I don't really know about that one.

**Comment by SirFinrod** [comment]
what about typical email type, tick the box and delete kinda thing?

**Comment by jhovgaard** [comment]
Based on the amount of emails you receive in the game now, I don't think this is relevant anymore.
