### ISSUE TITLE
Allow player to add multiple tasks for late-game managers as a queue

### ISSUE THREAD

**Issue by Memphoyles** [hovgaardgames/startupcompany#214]
Example:

A developer is making the UI Component. When the UI Component reaches a limit you set, he/she automatically switches to another component, say Backend Component. But he must be hooked to a manager.

**Comment by SirFinrod** [comment]
I mean that would be nice. but i think some employee type should do it. like a storage manager person. Nice idea indeed

**Comment by jhovgaard** [comment]
I was considering something similar to this. Let me pitch it:

Intermediate and Expert managers can select up to 3 and 5 components that the "team" should produce. The manager will then automatically assign the correct job/component to every employee he manages. 

This feature could be combined with inventory limitations and prioritized components.

Feedback please.

**Comment by SirFinrod** [comment]
In current versions i can increase my developer number one by one but with this kind of  mechanic i would be forced to hire them in 3s or 5s in order to reach maximum efficency. In other cases like if i were to assign 5 different kinds of employees it would be easier to maintain control because i can choose whatever employee type is doing what component which is simply what we are doing now, I dont know kinda tricky mechanic to balance i guess but im ok with this and it would be nice to control 3 or 5 same type of employees at once

**Comment by jhovgaard** [comment]
@SirFinrod It would be totally up to you how you put the team together. You can continue to use the auto-repeat feature.

**Comment by Memphoyles** [comment]
@jhovgaard Yes! That sounds great!

**Comment by roastchicken** [comment]
I think your idea sounds good @jhovgaard

**Comment by BrutalCSkakan** [comment]
I APPROVE

**Comment by jhovgaard** [comment]
Haven't seen much feedback related to this, so I'm closing the issue.
