### ISSUE TITLE
Playtester discussion

### ISSUE THREAD

**Issue by SirFinrod** [hovgaardgames/startupcompany#218]
Maybe because im a new playtester but the way i see things :  

Every playtester plays the game and find bugs and errors and makes suggestions. 

So i thought we can make like voice or text chat meetings where playtesters discuss some suggestions to how to make them better or even they are good suggestions. Just a thought. Please comment and let me know what you guys think about this :)

**Comment by InDieTasten** [comment]
The problem with voice meetups is that there is no chance for people who couldn't be there to catch up, unless somebody is writing a summary along the way. I feel like the current workflow is just fine: Create issue, and I will flag them with discussion if I feel like it there could be controversy regarding certain enhancements feature etc.
You can take a look at the discussions label. Those are all things, that haven't been decided yet. You can of course have an unofficial discussion about it in voice channels, and present your results as comment in the issue flagged as discussion.
There are many discussion labels out there right now. Lots of stuff to discuss, evaluate and test.
The thing is: A discussion can only ever be closed by @jhovgaard . He will always be the one with the final decision, and hence his feedback and considerations are very important so it would be helpful if jonas were to participate in these meetups which I don't think is going to happen due to limit of time.

I think Jonas will come up with something for all the discussion. Maybe one dedicated stream with some polls or just chat suggestions in general, which would basically be what you are describing, but with a very low frequency. Like maybe every 6 weeks or something.

**Comment by jhovgaard** [comment]
Great issue @SirFinrod. It's indeed a problem.

I agree with @InDieTasten, voice meetups is too inefficient. The discussion labels are great. Right now most of them are "dead" because I don't pay attention to them.

I'll go through all of the discussion issues now and keep them active in the future. Let's reopen this issue later if the problem consists.
