### ISSUE TITLE
Quick delivered contract should give a bonus

### ISSUE THREAD

**Issue by jhovgaard** [hovgaardgames/startupcompany#241]
For example: Delivered within 10% of the time gives a 10% bonus.

**Comment by ellbristow** [comment]
Doesn't need to be a big bonus. Maybe 5-10%, and only if delivered within, say, 6 hours of accepting the contract

**Comment by InDieTasten** [comment]
The timeframe for bonus should be relative to the normal contract time, just like jonas suggested. There is no need to set a fixed time frame of 6 hours, because it would limit this functionality to early game, where contracts are small enough to be finished within 6 hours.

Also, I think the bonus should no be monetary, but reputation based. There will be no company in the world giving you more money for a contract already signed, just because you deliver before deadline. But they will probably be so satisfied with your service, that they will likely consider you for other projects more easily.
