### ISSUE TITLE
Windows - Move the save folder

### ISSUE THREAD

**Issue by PeachIceTea** [hovgaardgames/startupcompany#251]
Currently the save folder is simply put into the Documents folder of the user. Some games us the "My Games" folder, like Fallout, Civ, Final Fantasy XIV, since the Documents folder wasn't originally made for this. It's kind of a loosing battle really since it's already cluttered with all kinds of misplaced crap that should have been stored into the AppData folder. But while it's now to late to correct the mistakes of our ancestors we don't have to repeat them, do we?

**Comment by BrutalCSkakan** [comment]
The argument is that "all of the other games avoid the My Games folder, therefore we do it too". 
I don't know how this will be later, but as we are greenlit and going to be a Steamgame, then the files probably will be saved in Steamapps anyway? Or maybe the cloud?

**Comment by PeachIceTea** [comment]
Well, the problem with the argument "all of the other games avoid the My Games folder, therefore we do it too" is that it is simply not true. I named a few games that use it and could find more if I would go and look for them.

As to how it will be later. It will stay exactly on how jhovgaard decides. Steam doesn't provide a fixed place to put your savefiles and saving stuff to the Steam Cloud doesn't mean that you don't need a local copy.

**Comment by InDieTasten** [comment]
I think "My Games" folder is mighty fine. One could allow a setting to customize that path. I really like it. It doesn't clutter the documents folder of "real" documents, keeping it nice and tidy, while still preserving the saves in a fairly safe spot. While the user directory is already pretty safe, I would argue that e.g. backup solutions that only backup a part of your files are more likely to preserve the users documents folder, than the appdata directoy.

Ultimately the documents folder with all it's sub-directories can be thought of as a place, in which documents are located, that require a comparatively larger amount of time to create. Writing a book, doing spreadsheets, whatever it is. It's really a pain to loose all those. As is losing savegames. They too can take a lot of time to create / advance. That's the reason why I wouldn't choose a directory outside documents folder.

Now whether or not it's going to be inside of My Games folder or is not that important to me. If I had to make this change to all of the games that exist for windows machines, I would go for "My Games" folder. But since there are so many games that have taken either choice, it's really not important. There will always be savegames in both locations.

Thats what I think about this topic.

**Comment by jhovgaard** [comment]
Anyone knows if "My Games" is localized on different Windows versions?

**Comment by BrutalCSkakan** [comment]
For me it is:
C:\Users\Kim\Documents\My Games

**Comment by InDieTasten** [comment]
"My Games" is not shipped with windows and hence not localized. The first game starting to save there generally creates this directory. Btw, all 3 games I I have currently installed save their files in "My Games", which are

- F1 2016
- Rocket League
- Tabletop Simulator

:3

**Comment by InDieTasten** [comment]
![image](https://cloud.githubusercontent.com/assets/7047377/23458345/3c975618-fe7c-11e6-98fe-ad52b9ecda42.png)

You actually don't have to worry about localizations:
![image](https://cloud.githubusercontent.com/assets/7047377/23458384/60b12fce-fe7c-11e6-9fd3-6df6cad0b51a.png)

**Comment by jhovgaard** [comment]
Alright, awesome! I'm locking the discussion now. Vote with 👍 👎  on OP.

**Comment by jhovgaard** [comment]
I'm changing this to `%USERPROFILE%/Saved Games/` as it's the only one supported by Steam Cloud save. Sorry guys :-)

**Comment by jhovgaard** [comment]
Done.
