### ISSUE TITLE
Loading Window Blank - Unable to Load Saved Games (Win10)

### ISSUE THREAD

**Issue by vanillapcstrategy** [hovgaardgames/startupcompany#503]
Unable to load save games from B12. I was informed of the dual directory thing from Discord and my files were not synchronized there. I synchronized them in both directories, no luck. Even uninstalled, reinstalled, and copied into directories with no luck.

[vpcs save files unable to load.zip](https://github.com/hovgaardgames/startupcompany/files/1220347/vpcs.save.files.unable.to.load.zip)

**Comment by bartusek27** [comment]
Hi QuantumHusky,

first off, thank you so much for your report!
Can you provide the errors from the console, so we can know exactly where is problem?
You can open console by pressing `F12`.

Once again, thank you for this report and have fun playing Startup Company!
Take care,
bartusek27

**Comment by vanillapcstrategy** [comment]
I'm not sure where you got QuantumHusky, but that's probably a better name than I chose. :)
![sc error 1](https://user-images.githubusercontent.com/30967425/29248246-593fd466-7fc8-11e7-993f-682cbc603131.jpg)

**Comment by johannwagner** [comment]
Hey vanillapcstrategy, 

your bug is the same bug of #446, which is caused by a corrupt `options.json` file. In the other thread, there is a workaround to get this thing fixed. I can open your savegame on my machine without problems !

Thanks again for your report and I hope, the other thread contains a solution for you. I will mark this bug as supercritical to make sure Jonas is going to see and fix it.

Regards, 
   Johann

**Comment by johannwagner** [comment]
Sorry, content of #446 is not there. Let me investigate!

**Comment by jhovgaard** [comment]
Fixed this one. Was caused by the game trying to load dton files. I made a fix, planned for next update
