### ISSUE TITLE
Upgrading from basic to intermediate levels

### ISSUE THREAD

**Issue by Mikeace1** [hovgaardgames/startupcompany#526]
Hello,

The upgrade increase in effectiveness is so low as to make firing the employees and hiring new ones more valuable, despite the loss in motivation.  Having the ability for employees to train and gain effectiveness might be a great addition.

**Comment by MazeBank** [comment]
Hi There!
I see this as a really good idea!
What do you mean with: "_Having the ability for employees to train and gain effectiveness_"
- This will "Free" upgrade them at speed?
- This will "Cost" {Amount} of money to "Train" these employees.

I see point 2 should be the best if you did mean that, I completely agree with your this would be great!

Also, I would like to add:
It may be a good add-on to this if they "Disappear" for 3 days or something.
To actually "Train" these employees.

Anyways!
Good add-on.

Kind regards Jason AKA MazeBank

+1

**Comment by AnnaisFay** [comment]
There's a few ways to motivate your employees in the game right now.

1) Send them somewhere nice on a 3 days vacation. Maybe some sunny place? :)

2) Put office decorations, chairs, sofas and much more! They will surely appreciate it.

3) Give them benefits! Who doesn't like a free gym membership? 

I do agree that training employees would be a nice thing in the future, but the tips above should help for now. When you come to late game, it will be horrible for your monthly income having to send tons of employees on vacation at the same time due to low mood (cause you fired people) :D 

Regards
Anna

**Comment by Mikeace1** [comment]
I believe it should cost money and time.  For example: 
5% increase - 1 day out - $5k
10% increase - 2 days out - $9k
And so on.  

You can also schedule HR related events where all the employees go to a training event (team building) and gain a set level of effectiveness.

The key is to make it accessable but not too overwhelming valuable that it throws off the game.

Also, giving them the option of sending a group on vacation it taking (i.e. designers or managers).

Hope that helps.

**Comment by MazeBank** [comment]
Hello @Mikeace1,
I see this and I thought: "You can get other bonuses for going on these "Team building events"
I see that as a great suggestion as well and I hope to see this implemented soon.

Jason <b>MazeBank/b>
Thank you for your suggestion

**Comment by BitCaps** [comment]
Training should be limited to beginner and possibly intermediate employees.  Experts can not be improved further.  Beginners should receive a greater benefit from training than intermediate.

**Comment by AdwinVL** [comment]
Great idea Mike!

**Comment by jhovgaard** [comment]
Fixed with the new training feature.
