### ISSUE TITLE
Bug: working hours

### ISSUE THREAD

**Issue by BitCaps** [hovgaardgames/startupcompany#559]
I can reproduce this bug with each new hire. 

I hire an employee, assign a manager, then reduce their work day by one hour (reduce end time by one).  At the end of the day I advance to the next day.  When the employee arrives at work on day 2, the change made to the employee work hours was not saved.  It has returned to an 8 hour day.  

The second time I change it, on day 2, it is saved and remains at 7 hours for the rest of the game.

**Comment by MazeBank** [comment]
Hello @BitCaps 
First of all, thank you for the report but!
You cannot change work schedule by only using a manager.
In fact, you can change working hours with a mod called "Wolf Pack".
If you are using this mod then there is no reason to report this bug.
If you are not can you please provide me with some screenshots of the work schedule and your HR Manager interface so it becomes more clear to me.

Otherwise, thank you for reporting if you have any further questions feel free to ask.

<Jason/t>

**Comment by BitCaps** [comment]
I also have an HR Manager, so I can change work schedules for employees.   I do not have any mods.

The work schedule reverts back to an 8 hour day after one day passes from day of hiring.  Any changes I make after that are fine.

**Comment by MazeBank** [comment]
Hi again,
I will pass this through.

Thanks for the report.
If you have any further questions feel free to ask me!

<Jason/t>
