### ISSUE TITLE
my game doesnt save

### ISSUE THREAD

**Issue by tanecito** [hovgaardgames/startupcompany#586]
I was playing for 2 hours with out any problems (just baught the game from steam) no mods installed and sudenly the game crashes and I thought to my self o maybe it has autosave but unfortunatly it didnt save at all. I tried making another one I reached the same level and some where like the same income but I thought to my self if it crashes again? so I thought that exiting the game was going to save my game but it didnt. I made another one again really fast and searched everywhere the save button but there is non 
(btw nice game)

**Comment by johannwagner** [comment]
Hey, 

I read your bug report carefully and I wasn't able to reproduce the bug. 
We need more information about your game version and your build number, which is located at Steam -> Startup Company -> Properties -> Local Data.

Startup Company saves game every ten seconds. Save games are located under 'C:/Users/tanecito/Saved Games/Startup Company'. Do you see `*.json` files?

This bug is maybe related to #446. 

Heads up! Most bugs are resolved within two weeks. 
If you think, that I closed your bug without reason, please message me on Discord (TupperBox).

Regards, 
    Johann
